### ISSUE TITLE
E: Package 'libhdf5-100' has no installation candidate

### ISSUE THREAD

**Issue by SRGWML** [nathanrooy/rpi-urban-mobility-tracker#11]
Instructions for "First install the required dependencies for cv2" guide the end use to install libhdf5-100 via `sudo apt-get install libhdf5-dev libhdf5-serial-dev libhdf5-100`

Output of the above command/instruction on Raspberry Pi OS:
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libhdf5-dev' instead of 'libhdf5-serial-dev'
Package libhdf5-100 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libhdf5-103

E: Package 'libhdf5-100' has no installation candidate
`
Before installation the latest Raspberry Pi OS was installed, updated, and upgraded. The package libhdf5-103 was installed in leau of libhdf5-100 but resulting usage of umt produces errors for -camera.

Guidance or perhaps update instruction set?

**Comment by nathanrooy** [comment]
Hi @SRGWML, there are some recent errors associated with the DeepSort implementation when running on a rpi. I would recommend pulling from an earlier time as a quick fix: https://github.com/nathanrooy/rpi-urban-mobility-tracker/tree/48172ccb050c0f64289526e4063aa431aca602d4

I'm currently working on a permanent solution...

**Comment by bafs84** [comment]
Following [this stackoverflow](https://stackoverflow.com/questions/59080094/raspberry-pi-and-opencv-cant-install-libhdf5-100) threat I tried to get libhdf5-100 running. So after activating the virtual environment with 

`sudo apt-get install virtualenv`
`virtualenv -p python3.7 venv_umt`
`source venv_umt/bin/activate`

I tried:
`pip install opencv-contrib-python==4.1.0.25`

and continued the original installation process without errors, but when I try to run the example I get an error that it was not found.

`(venv_umt) pi@coral1:~ $ umt -camera -modelpath pednet_20200326_tflite_graph.tflite -labelmap labels.txt
2020-12-29 09:58:18.300536: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/pi/venv_umt/bin/umt", line 8, in <module>
    sys.exit(main())
  File "/home/pi/venv_umt/lib/python3.7/site-packages/umt/umt_main.py", line 51, in main
    if args.model_path: assert os.path.exists(args.model_path)==True, "can't find the specified model..."
AssertionError: can't find the specified model...`

**Comment by nathanrooy** [comment]
This should be resolved using the new Docker installation method.
