### ISSUE TITLE
Dockerize install and reduce deployment friction.

### ISSUE THREAD

**Issue by nathanrooy** [nathanrooy/rpi-urban-mobility-tracker#14]

**Comment by hainesdata** [comment]
Does not work with armv6l architecture. I rewrote the Docker commands in a shell script file and fixed most incompatibilities with armv6l (for Pi Zero users). The only thing missing is an armv6l wheel for tflite. Everything else works fine in the install.

**Comment by nathanrooy** [comment]
Finished.
