### ISSUE TITLE
Viewing output in real time

### ISSUE THREAD

**Issue by GOBish** [nathanrooy/rpi-urban-mobility-tracker#3]
Hi,

Is there a way to view the tracking in real time instead of just seeing the saved images in the output folder when using the -display option?

**Comment by nathanrooy** [comment]
This is not possible currently, but it would be fairly easy to implement. I can start working on this feature.

**Comment by nathanrooy** [comment]
@GOBish, a live view mode is now available. Simply append the flag `-display` when running.

**Comment by GOBish** [comment]
Thank you! I will check it out now.
