### ISSUE TITLE
frame rate while using TPU?

### ISSUE THREAD

**Issue by GOBish** [nathanrooy/rpi-urban-mobility-tracker#4]
When using the edgeTPU (-tpu option) and -display option, I am getting frame rates of only 1 FPS or so. Is this expected? I would have expected better performance.

Thanks!

**Comment by nathanrooy** [comment]
Yes, that sounds about right. If you drop the `-display` flag it should reach ~10fps on an rpi.

**Comment by GOBish** [comment]
That is interesting -- I would have expected a higher frame rate with RPi 4 (4gb) + Coral EdgeTPU. Using a mobilenet model I get >30fps with object detection and my experiments with SORT in the past have not significantly slowed that.
