### ISSUE TITLE
Main tracking loop failing with pednet_20200517.tflite

### ISSUE THREAD

**Issue by kfculligan** [nathanrooy/rpi-urban-mobility-tracker#6]
(github newbie here, so please pardon if I'm using this incorrectly).

Great project here. Thank you. I am running the example on a RPI 3B and can get the code to work with the default model, but when using the latest PedNet (pednet_20200517.tflite) the main tracking loop fails at the try/except section ("TRACKER FAILED"). I removed the try/except to see the actual error and this is the result:

Traceback (most recent call last):
  File "/home/pi/venv/bin/umt", line 8, in <module>
    sys.exit(main())
  File "/home/pi/venv/lib/python3.7/site-packages/umt/umt_main.py", line 89, in main
    tracker_labels, tracker_scores = match_detections_to_labels_and_scores(new_dets, trackers, scores, classes, labels)
  File "/home/pi/venv/lib/python3.7/site-packages/umt/umt_utils.py", line 162, in match_detections_to_labels_and_scores
    matched_labels = [labels[item] for item in matched_classes]
  File "/home/pi/venv/lib/python3.7/site-packages/umt/umt_utils.py", line 162, in <listcomp>
    matched_labels = [labels[item] for item in matched_classes]
KeyError: 3

**Comment by kfculligan** [comment]
I added one extra row to label.txt for pednet as a trial and now it seems to work. Now I just need to get the labels to match up.

**Comment by nathanrooy** [comment]
@kfculligan any luck with the labels?

**Comment by mlopezgez** [comment]
Change "net/%s:0" => "%s:0" 81 & 85 lines in `umt/deep_sort/generate_detections.py`

**Comment by Back-Pack-Jack** [comment]
@nathanrooy @kfculligan 
I believe these issues are related : #13 and that I've identified and the issue
